require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - db/schema.rb
    - bin/*
    - vendor/**/*
    - db/**/*
    - config/*.rb
    - config/**/*
    - config.ru
    - Rakefile

Metrics/BlockLength:
  Exclude:
    - "**/config/**/*.rb"
    - "**/spec/**/*.rb"
    - "**/app/views/**/*"

Style/CollectionMethods:
  PreferredMethods:
    find: detect
    reduce: inject
    collect: map
    find_all: select

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/BlockDelimiters:
  EnforcedStyle: line_count_based

Layout/DotPosition:
  EnforcedStyle: leading

Rails/FilePath:
  EnforcedStyle: arguments

RSpec/RepeatedExampleGroupDescription:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false
